# Generated by Django 3.2.7 on 2021-11-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_games',
            old_name='Screen_shot_tree',
            new_name='Screen_shot_three',
        ),
    ]
