# Generated by Django 3.2.7 on 2021-11-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_auto_20211107_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='image_one',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='comics',
            name='image_two',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
