# Generated by Django 3.2.7 on 2021-11-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_auto_20211107_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='title',
            field=models.TextField(max_length=60),
        ),
    ]
