# Generated by Django 3.2.7 on 2021-11-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_filtercomics'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='isdatel',
            field=models.TextField(default=2, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filtercomics',
            name='mark',
            field=models.IntegerField(),
        ),
    ]
