# Generated by Django 3.2.7 on 2021-11-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_alter_comics_isdatel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='image_one',
            field=models.ImageField(upload_to='img/comics/'),
        ),
        migrations.AlterField(
            model_name='comics',
            name='image_two',
            field=models.ImageField(upload_to='img/comics/'),
        ),
    ]
